FROM node:20-alpine

ARG API_CONTAINER_URL
ARG API_CLIENT_URL
ARG API_TOKEN

WORKDIR /frontend

RUN npm install pm2 -g

COPY package*.json ./

RUN npm ci --omit=dev

COPY . ./

ENV API_CONTAINER_URL=${API_CONTAINER_URL}
ENV API_CLIENT_URL=${API_CLIENT_URL}
ENV API_TOKEN=${API_TOKEN}

RUN npm run build

EXPOSE 3000

CMD [ "pm2-runtime", "npm", "--", "start"]