FROM node:20-alpine

ARG API_CLIENT_URL

WORKDIR /strapi

RUN npm install pm2 -g

COPY package*.json ./

RUN npm ci --omit=dev

COPY . ./

ENV API_CLIENT_URL=${API_CLIENT_URL}

RUN npm run build

EXPOSE 1337

CMD [ "pm2-runtime", "npm", "--", "start"]