FROM nginx:alpine

RUN apk update && apk add --no-cache curl

COPY default.conf /etc/nginx/default.conf
COPY nginx.conf /etc/nginx/nginx.conf

COPY healthcheck.frontend.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/healthcheck.frontend.sh
ENTRYPOINT ["/usr/local/bin/healthcheck.frontend.sh"]

EXPOSE 80 443