FROM node:22-alpine

RUN npm install -g pnpm@latest

ARG API_CLIENT_URL

WORKDIR /strapi

COPY package.json pnpm-lock.yaml ./

RUN pnpm install

COPY . ./

ENV API_CLIENT_URL=${API_CLIENT_URL}

RUN pnpm run build

EXPOSE 1337

CMD ["pnpm", "run", "start"]